sudo: required
dist: trusty
group: deprecated-2017Q3
os: linux
language: generic
cache:
  apt: true
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - MAKEJOBS=-j5
  - RUN_TESTS=false
  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
  - CCACHE_SIZE=400M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - PYTHON_DEBUG=1
  - WINEDEBUG=fixme-all
  matrix:
  - HOST=arm-linux-gnueabihf PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-arm-linux-gnueabihf"
    DEP_OPTS="NO_QT=1" CHECK_DOC=1 GOAL="install" MOTION_CONFIG="--enable-glibc-back-compat
    --enable-reduce-exports"
  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PPA="ppa:bitcoin/bitcoin"
    PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.7 bc" GOAL="install" MOTION_CONFIG="--enable-gui
    --enable-reduce-exports" MAKEJOBS="-j4" WINE=true
  - HOST=i686-pc-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq"
    DEP_OPTS="NO_QT=1" GOAL="install" MOTION_CONFIG="--enable-zmq --enable-glibc-back-compat
    --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/motion" PYZMQ=true
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PPA="ppa:bitcoin/bitcoin"
    PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.7 bc" GOAL="install" MOTION_CONFIG="--enable-gui
    --enable-reduce-exports" MAKEJOBS="-j4" WINE=true
  - HOST=x86_64-unknown-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="bc python3-zmq"
    DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" GOAL="install" MOTION_CONFIG="--enable-zmq
    --enable-glibc-back-compat --enable-reduce-exports" CPPFLAGS="-DDEBUG_LOCKORDER
    -DENABLE_MOTION_DEBUG" PYZMQ=true
  - HOST=x86_64-unknown-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="python3" DEP_OPTS="NO_WALLET=1"
    GOAL="install" MOTION_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST=x86_64-apple-darwin11 PPA="ppa:bitcoin/bitcoin" PACKAGES="cmake imagemagick
    libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" MOTION_CONFIG="--enable-gui
    --enable-reduce-exports" OSX_SDK=10.9 GOAL="deploy"
before_install:
- git clone https://github.com/motioncrypto/x16r_hash
- travis_retry sudo apt-get install python-dev
- travis_retry sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
install:
- if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
- if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
- cd x16r_hash && python setup.py install --user && cd ..
before_script:
- unset CC; unset CXX
- unset DISPLAY
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- MOTION_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
- "./configure --cache-file=config.cache $MOTION_CONFIG_ALL $MOTION_CONFIG || ( cat
  config.log && false)"
- make distdir PACKAGE=motion VERSION=$HOST
- cd motion-$HOST
- "./configure --cache-file=../config.cache $MOTION_CONFIG_ALL $MOTION_CONFIG || (
  cat config.log && false)"
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
- if [ "$RUN_TESTS" = "true" -a "$WINE" != "true" ]; then travis_wait 30 make $MAKEJOBS
  check VERBOSE=1; fi
- if [ "$RUN_TESTS" = "true" -a "$WINE" = "true" ]; then wine  src/test/test_motion.exe
  --log_level=test_suite; fi
- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
after_script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then (echo "Upload goes here. Something like: scp
    -r $BASE_OUTDIR server" || echo "upload failed"); fi
deploy:
  provider: gcs
  access_key_id: GOOGYOYYAVSJFNBHOBJC
  secret_access_key:
    secure: p1m/as/PTV68KhEy0YKWdFSpmTVw3jWLR0eYFgrYCvfjK+Eig8bsoDt3Q0Pm/n4ikqhH8b8TORzjYITMOZqw7+za9lS5M/uAD1Hj8ld4JCA7/eEf9aVAyBnIW8Pt7wtXjuVdYeMqkXu1ZChvJ2eNt/Q5wC7rKCcbRfmpY59hfzTiLSz/DLo12b2pBEA08oueg6XAYSMiKzvxy83N+7r1pxG/huczAxTTIJ6DqSuJ94hX7PEVl4B7YuqeAAdjoG308P8BaHUg7zlsSOjB+TJDlLV5MS3C3acmFOFziG3dDTKtAFqjBYFh7lUp2Iud0VygAQUtiSDLh2iNUs6tlr5i0079fhNq7kUOqxRqLa+6yYL4aMM7gXt+GNRKkoxd3nX27VTahgXc2bAssorMrj0VD2IuTmDxYd5hBClu0le/pu5MWb3IhcFYRY7KwxgqB4KxF1/IW5xorZh0+oGCcW41SyPXivyH4pM0CLwuMgj/DDaBu1aMyvXzisZ/oI5oimf6OD+K/B+uJgChxgxDU+davCbTU13aGQgbm9rJ64Q8olI8hTOHBDf2ubaUMxNv0ucAW4aB8QotDuz1uO5mkKO8WQCqd8w6FJw1tUyMrm/NX0zO8njxBj7nx4vDMTjm0ZedGjkMrNmI7HhN2iXqLA/ExFWZLUYro1N/zsbOxV8gq4I=
  bucket: motioncrypto-release
  on:
    repo: motioncrypto/motion
  skip_cleanup: true
